import bpy

def unregister_props():
    unregister = [
        lambda: delattr(bpy.types.Scene, "socket_action_selector"),
        lambda: delattr(bpy.types.Scene, "socket_create_location"),
        lambda: delattr(bpy.types.Scene, "custom_gim_bool"),
        lambda: delattr(bpy.types.Scene, "custom_gim_location"),
        lambda: delattr(bpy.types.Scene, "custom_gim_remote_path"),
        lambda: delattr(bpy.types.Scene, "neox_mod_export_custom_skeleton"),
        lambda: delattr(bpy.types.Scene, "neox_mod_export_create_mod_json"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_main_gim"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_dual_gim"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_trigger_text"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_triggers"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_trigger_index"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_regex_text"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_animation_name_cache"),
        lambda: delattr(bpy.types.Scene, "neox_dual_form_animation_name_cache_source"),
        lambda: delattr(bpy.types.Scene, "neox_mod_name"),
        lambda: delattr(bpy.types.Scene, "skeleton_path"),  
        lambda: delattr(bpy.types.Scene, "animconfig_location"),  
        lambda: delattr(bpy.types.Scene, "animconfig_path"),  
        lambda: delattr(bpy.types.Scene, "skip_unnecessary_animconfig_files"),
        lambda: delattr(bpy.types.Scene, "animconfig_selector"),
        lambda: delattr(bpy.types.Scene, "gim_selector"),          
        lambda: delattr(bpy.types.Scene, "neox_rig_selector"),
        lambda: delattr(bpy.types.Scene, "flip_uv_y"),
        lambda: delattr(bpy.types.Scene, "neox_mesh_selector"),
        lambda: delattr(bpy.types.Scene, "neox_mesh_import_source"),
        lambda: delattr(bpy.types.Scene, "neox_remote_gim_path"),
        lambda: delattr(bpy.types.Scene, "neox_remote_import_sockets"),
        lambda: delattr(bpy.types.Scene, "neox_socket_filters_enabled"),
        lambda: delattr(bpy.types.Scene, "neox_socket_filter_bone_names"),
        lambda: delattr(bpy.types.Scene, "neox_socket_filter_socket_names"),
        lambda: delattr(bpy.types.Scene, "neox_socket_filter_socket_match_type"),
        lambda: delattr(bpy.types.Scene, "neox_animation_selector"),
        lambda: delattr(bpy.types.Scene, "neox_animation_import_source"),
        lambda: delattr(bpy.types.Scene, "neox_remote_animation_path"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_mode"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_gim_path"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_animation_name"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_selector"),
        lambda: delattr(bpy.types.Scene, "neox_animation_skeleton_preset"),
        lambda: delattr(bpy.types.Scene, "neox_animation_custom_skeleton_path"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_loop"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_fps"),
        lambda: delattr(bpy.types.Scene, "neox_animation_export_reduce_keys"),
        lambda: delattr(bpy.types.Scene, "neox_animation_position_tolerance"),
        lambda: delattr(bpy.types.Scene, "neox_animation_scale_tolerance"),
        lambda: delattr(bpy.types.Scene, "neox_animation_rotation_tolerance_degrees"),
        lambda: delattr(bpy.types.Scene, "frame_dump_selector"),
        lambda: delattr(bpy.types.Scene, "migoto_export_selector"),
        lambda: delattr(bpy.types.Scene, "neox_export_selector"),
        lambda: delattr(bpy.types.Scene, "clean_ini"),
        lambda: delattr(bpy.types.Scene, "export_all_relative_meshes"),
        lambda: delattr(bpy.types.Scene, "clear_unused_materials"),
        lambda: delattr(bpy.types.Scene, "migoto_save_fmt_file"),
        lambda: delattr(bpy.types.Scene, "custom_metal"),
        lambda: delattr(bpy.types.Scene, "custom_normal"),
        lambda: delattr(bpy.types.Scene, "metal_selector"),
        lambda: delattr(bpy.types.Scene, "normal_selector"),
        lambda: delattr(bpy.types.Scene, "metal_slot_selector"),
        lambda: delattr(bpy.types.Scene, "normal_slot_selector"),
        lambda: delattr(bpy.types.Scene, "idvmi_update_status"),
        lambda: delattr(bpy.types.Scene, "idvmi_update_latest_version"),
        lambda: delattr(bpy.types.Scene, "idvmi_update_latest_url"),
        lambda: delattr(bpy.types.Scene, "idvmi_update_download_url"),
        lambda: delattr(bpy.types.Scene, "idvmi_update_available"),
        lambda: delattr(bpy.types.Scene, "namespace_textbox"),
        lambda: delattr(bpy.types.Scene, "neox_action_selector"),
        lambda: delattr(bpy.types.Scene, "migoto_action_selector"),
        lambda: delattr(bpy.types.Scene, "migoto_cb_pose_start_index"),
        lambda: delattr(bpy.types.Scene, "migoto_cb_pose_end_index"),
        lambda: delattr(bpy.types.Scene, "migoto_cb_pose_batch_import_related_meshes"),
        lambda: delattr(bpy.types.Scene, "migoto_mesh_import_mode"),
        lambda: delattr(bpy.types.Scene, "migoto_use_standard_model_format"),
        lambda: delattr(bpy.types.Scene, "migoto_import_all_related_txt"),
        lambda: delattr(bpy.types.Scene, "migoto_import_all_related_buf"),
        lambda: delattr(bpy.types.Scene, "migoto_import_all_related"),
    ]

    for function in unregister:
        try:
            function()
        except AttributeError:
            pass
